### PR TITLE
feat: bump the peer dependency version of react-native-performance

### PR DESCRIPTION
**Pull request by allroundexperts**
### Details

This PR updates the version of `react-native-performance` peer dependency from `4.0.0` to `5.1.0`.

### Related Issues

https://github.com/Expensify/App/issues/26987

### Automated Tests

N/A

### Linked PRs

https://github.com/Expensify/App/pull/27289

### CODE REVIEW

**Comment by techievivek** [comment]
Not sure why @marcochavezf was not assigned here, do we not have react-native-onyx repo as part of the automation?

**Review by techievivek — APPROVED** [review]

**Comment by techievivek** [comment]
Not an emergency merge, tests were passing.
Screenshot 2023-09-14 at 9 12 05 AM

**Comment by techievivek** [comment]
@allroundexperts You will now need to update the onyx version in App repo.

**Comment by blazejkustra** [comment]
@allroundexperts Can you link the PR that updates react-native-performance in the App? Asking as it is blocking one of my PR

**Pull request merged**
