### PR TITLE
fix: 10622 android metrics crash

### PR DESCRIPTION
**Pull request by christianwen**
### Details

This fixes the crash when we enable
```
ONYX_METRICS=true
CAPTURE_METRICS=true
```
Please refer to this [accepted proposal](https://github.com/Expensify/App/issues/10622#issuecomment-1253220762) for more details

### Related Issues

https://github.com/Expensify/App/issues/10622

### Automated Tests

This is a bug fix, no new behavior is introduced so I didn't add tests.

### Linked PRs

Will update when a new Onyx version with this change is released, I assume there'll be another PR to bump the Onyx version in https://github.com/Expensify/App

### Screenshots
Screenshots showing no crash happens in any platform after the fix

#### Web

Screen Shot 2022-10-13 at 17 57 55

#### Mobile Web

Screen Shot 2022-10-13 at 17 58 45

#### Desktop

Screen Shot 2022-10-13 at 17 28 09

#### iOS

Simulator Screen Shot - iPhone 13 - 2022-10-13 at 17 21 27

#### Android

processed

### CODE REVIEW

**Comment by christianwen** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by christianwen** [comment]
recheck

**Comment by puneetlath** [comment]
@Santhosh-Sellavel and I should review this.

**Comment by Santhosh-Sellavel** [comment]
@christianwen  

Seems this test is relevant to this issue, wondering should this test had to be failed earlier.
https://github.com/Expensify/react-native-onyx/blob/961320c3743f1d2902b044478eaddc2667d58704/tests/unit/onyxMetricsDecorationTest.js#L57-L79

Anythoughts?

cc: @puneetlath

**Comment by christianwen** [comment]
@Santhosh-Sellavel that test doesn't fail because it's using the `react-native` implementation in `lib/metrics/index.native.js`, it's not using the noop in `lib/metrics/index.web.js`

**Comment by Santhosh-Sellavel** [comment]
Are we missing unit tests for the web?

**Comment by Santhosh-Sellavel** [comment]
@puneetlath Any thoughts on this https://github.com/Expensify/App/issues/7862

**Comment by Santhosh-Sellavel** [comment]
@puneetlath Any thoughts on this https://github.com/Expensify/react-native-onyx/pull/198#issuecomment-1278189881

**Comment by puneetlath** [comment]
Agreed - can we add a test for the web scenario?

**Comment by Santhosh-Sellavel** [comment]
@christianwen any update?

**Comment by christianwen** [comment]
@Santhosh-Sellavel sorry I'll add the tests today, been a bit occupied this week

**Comment by christianwen** [comment]
@Santhosh-Sellavel unit test added, thanks

**Review by Santhosh-Sellavel — APPROVED** [review]
Looks good! Will test on PR against E/App.
All you @puneetlath @aldo-expensify

**Comment by puneetlath** [comment]
@christianwen can you please merge main.

**Comment by christianwen** [comment]
@puneetlath done, @Santhosh-Sellavel can give the review again. Please note there's the other merged PR https://github.com/Expensify/react-native-onyx/pull/206 that has one of the change in this PR (the Onyx.update change), so I've removed that redundant change in this PR as part of the conflict resolution

**Review by Santhosh-Sellavel — APPROVED** [review]

**Review by puneetlath — APPROVED** [review]

**Pull request merged**
