### PR TITLE
Update eslint-config

### PR DESCRIPTION
**Pull request by luacmartins**
### Details
Updates the eslint-config repo.

### Related Issues
https://github.com/Expensify/react-native-onyx/issues/136

### Automated Tests
Covered by lint and automated tests

### CODE REVIEW

**Comment by TomatoToaster** [comment]
Oh dang, lotsa changes but from skimming they looks good. I need just a little bit longer to review this.

**Comment by luacmartins** [comment]
Most changes are harmless (just adding commas, line breaks, etc). But there are a few that demand more attention 😅

**Review by TomatoToaster — APPROVED** [review]
Ok got it all, nice work!

**Comment by TomatoToaster** [comment]
@luacmartins Do we need to bump the version of react-native-onyx on NewDot/wherever else too?

**Pull request merged**
