### PR TITLE
Upgrade react-native to v0.71.2

### PR DESCRIPTION
**Pull request by priyeshshah11**
### Details

This PR upgrades the `react-native` version to v0.71.2 & also upgrades the `react-native-quick-sqlite` to v8.0.0-beta.2 as that includes the v0.71.2 upgrade.

### Related Issues

https://github.com/Expensify/App/issues/15124

### Automated Tests

No tests have been added as just upgrading the dependancy versions

### Linked PRs

https://github.com/Expensify/App/pull/15130 is dependent on this PR

### CODE REVIEW

**Comment by priyeshshah11** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by priyeshshah11** [comment]
@mountiny @roryabraham What's the best way to test this?

**Review by cristipaval — COMMENTED** [review]
LGTM, but how can we test this? Shall we just merge it and let Applause test the App?

**Comment by mountiny** [comment]
I think @marcaaron or @kidroca had some ways before how to test react-native-onyx with the App, do you have any tips here?

**Comment by marcaaron** [comment]
What is this related to? I see no linked issue.

**Comment by marcaaron** [comment]
One way to test this with the App repo is to just build the web dist with `npm run build` and then replace the entire `react-native-onyx` folder in `node_modules`.

**Comment by marcaaron** [comment]
native doesn't need to build but web does IIRC.

**Comment by kidroca** [comment]
Yes to what Marc suggests 
I have been doing this for ages, because `npm link` does not work with `metro` the bundler react-native uses (it does not follow symlinks)

When I work on Onyx, and I want to test changes in App I do the following:
- Use a tool that syncs my `projects/Expensify/react-native-onyx` to `projects/Expensify/App/node_modules/react-native-onyx`
- Make changes in Onyx project, then run the Onyx build script (`npm run build`)

If this is for a one time test, you can just build the Onyx project and then copy it over to `App/node_modules/` 
(You can also only copy `dist` and `lib`)
(Native doesn't have to build, it directly uses the code from `lib`)

**Comment by mountiny** [comment]
@priyeshshah11 Do these steps sound good? We should be able to test it with the RN update PR then

**Comment by priyeshshah11** [comment]
@mountiny yes the above mentioned steps worked & I was able to test web & it looks all good. Is there anything specific that I should be looking out for?

Thanks @kidroca & @marcaaron ❤️

**Comment by mountiny** [comment]
@priyeshshah11 I think we just want to test usual from through the app:
- create chat report
- send a message
- request money
- Create workspace
- send a message in the workspace chat
- invite a member to a policy
- upload profile picture

I think this should cover all the actions. Also SQLite is used in native device afaik so we should test this in web and also in native device 🙌

**Comment by priyeshshah11** [comment]
Tested the above on web but still waiting on testing this on native, currently blocked by errors on https://github.com/Expensify/App/pull/15130

**Comment by priyeshshah11** [comment]
Finally, was able to fix the native build errors & have tested the above & it all looks good. I think we should now merge this & release & then perform thorough testing on https://github.com/Expensify/App/pull/15130

**Review by cristipaval — APPROVED** [review]
I also tested and works well on my end.

**Comment by cristipaval** [comment]
@priyeshshah11 it looks like the commits are not signed and we can't merge this one. Could you please check?

**Comment by cristipaval** [comment]
Thank you!

**Pull request closed without merging**
