### PR TITLE
Use a map for Onyx collection keys

### PR DESCRIPTION
**Pull request by ospfranco**
### Details

This change was proposed, merged and reverted due to a failing test and some misscommunication. I've fixed the initial value of the collection map and that also fixes the tests.

[Revert PR](https://github.com/Expensify/react-native-onyx/pull/323)

This change also provides an improvements to the ReportScreen optimzations Margelo is currently working on.

### Related Issues

https://github.com/Expensify/react-native-onyx/pull/329

### CODE REVIEW

**Review by tgolen — APPROVED** [review]
Ah, using `Map()`. Nice!

**Comment by tgolen** [comment]
Could you please add screenshots showing that the App tests are passing with this change and the app builds?

**Review by cead22 — APPROVED** [review]
>Could you please add screenshots showing that the App tests are passing with this change and the app builds?

Approving, but waiting for Tim's request to be addressed before we merge

**Comment by ospfranco** [comment]
Here are the passing tests

CleanShot 2023-09-06 at 10 35 38

Here is a screenshot of metro and the app running

CleanShot 2023-09-07 at 09 01 53

**Comment by cead22** [comment]
@tgolen I think your concern is addressed. Wanna hit the button?

**Comment by mountiny** [comment]
Going ahead and ship this since we got all the approvals, thanks!

**Pull request merged**
