### PR TITLE
Remove string selector

### PR DESCRIPTION
**Pull request by hayata-suenaga**
### Related Issues

GH_LINK https://github.com/Expensify/react-native-onyx/issues/285

### Automated Tests

Removed some automated tests for string selectors.

### Linked PRs

https://github.com/Expensify/App/pull/23695

### CODE REVIEW

**Comment by srikarparsi** [comment]
Hey @hayata-suenaga! Seems like there's some lint errors

**Comment by hayata-suenaga** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by hayata-suenaga** [comment]
recheck

**Comment by hayata-suenaga** [comment]
closing this I think I run prettier accidentally in the first commit and I'm too lazy to revert 😓

**Pull request closed without merging**
