### PR TITLE
Have Onyx.clear() properly call collection callbacks which use waitForCollectionCallback

### PR DESCRIPTION
**Pull request by tgolen**
### Related Issues
Fixes https://github.com/Expensify/App/issues/13584

### Automated Tests
Covered in unit tests

### Linked PRs
The version will be updated in the PR for https://github.com/Expensify/App/issues/11671

### CODE REVIEW

**Review by yuwenmemon — DISMISSED** [review]
LGTM, thanks for figuring out this wrinkle!

**Review by amyevans — APPROVED** [review]
NAB: I see there's documentation for `notifySubscribersOnNextTick` in API.md, is it worth it to add `notifyCollectionSubscribersOnNextTick` there as well?

**Comment by tgolen** [comment]
Sure! I can rebuild the documentation.

Updated! There were a few more changes to the documentation that it grabbed which should be fine.

**Review by amyevans — APPROVED** [review]
Awesome, looks good!

**Pull request merged**
