### PR TITLE
[HOLD sqllite deployed to production] Add functionality for multiRemove()

### PR DESCRIPTION
**Pull request by tgolen**
### Related Issues
Fixes https://github.com/Expensify/Expensify/issues/251798

### Automated Tests
I added some, but it's difficult to test this fully with both data providers. I tested this by adding it to App and testing that signin/singout worked (especially on a large account)

### Linked PRs
https://github.com/Expensify/App/pull/13886

### CODE REVIEW

**Comment by yuwenmemon** [comment]
Should we also add a basic test for the `multiRemove` functionality itself?

**Comment by tgolen** [comment]
Thanks @yuwenmemon for the review!

I did add a couple of basic tests for `multiRemove()` in this PR, but were you thinking about more? I was discussing some other ways to test this in [this thread](https://expensify.slack.com/archives/C01GTK53T8Q/p1672268795157299?thread_ts=1671583867.011199&cid=C01GTK53T8Q) which basically ended with us feeling like the tests written here are enough.

**Comment by yuwenmemon** [comment]
I think that's fair. My only thought was maybe adding tests similar to what we have for [clear()](https://github.com/Expensify/react-native-onyx/blob/7f7f06b0637a458ed1306947c87a80eae27afdd0/tests/unit/onyxClearNativeStorageTest.js) and [multiMerge()](https://github.com/Expensify/react-native-onyx/blob/520329475c99b617317fbff489e54a2b60fe2728/tests/unit/onyxMultiMergeWebStorageTest.js)

Also sorry for screwing you on the line indentation with my suggestions 😅

**Comment by tgolen** [comment]
OK, I've actually been working on [this second PR](https://github.com/Expensify/react-native-onyx/pull/220/files) that fixes https://github.com/Expensify/App/issues/13884 and it looks like we aren't going to need `multiRemove()` after all. So, I think I am just going to close this and continue with the other PR

**Pull request closed without merging**
