### PR TITLE
Fix mergeCollection() mutability issue

### PR DESCRIPTION
**Pull request by marcaaron**
### Details
Made a bad assumption in the last PR so rolling back a change to re-use some logic and instead adding some mild duplication so we can unblock the IOU project.

### Related Issues
https://github.com/Expensify/Expensify.cash/issues/2225

### Automated Tests
Added the test (not written by me)

### CODE REVIEW

**Comment by marcaaron** [comment]
cc @Julesssss @AndrewGable if one of you want to also take a look

**Review by Julesssss — APPROVED** [review]
Confirmed the test case fails without the changes. Nice work

**Comment by Julesssss** [comment]
Merging without further reviewers as this is blocking some pretty critical N5 issues.

**Comment by Julesssss** [comment]
Reopening until version is bumped in .cash

**Pull request merged**
